spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exam_system?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
app:
  jwt:
    secret: my-very-strong-secret-key-with-at-least-32-characters
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
